### ISSUE TITLE
/me protocol

### ISSUE THREAD

**Issue by nathalie-tate** [OakAces/acechat-server#20]
At the prof's suggestion, I think we should implement a /me command

Same as the MSG protocol, should be easy to implement

```
{
  "command": "ME",
  "args": ["channel", "message text goes here"]
}
```
```
{
  "user": "username",
  "command": "ME",
  "args": ["channel", "message text goes here"]
  "timestamp": 1326439500 // Unix Timestamp
}
```

**Comment by dyladan** [comment]
this should be implemented client side. the way IRC clients typically do it is to wrap messages with the special characters: 

`/me barfs on the floor` is sent as: `\001ACTION barfs on the floor.\001`

For more information see the client to client protocl (CTCP)

**Comment by nathalie-tate** [comment]
okay, that makes sense. I was just thinking a protocol change would be better for clients that didn't support it, but I'll do this instead.
