### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by nathalie-tate** [OakAces/acechat-server#3]
- Server should send a message to all clients when a channel is created
- Server should send a message to a channel when a user joins or parts
- when a user sends a message to a channel, the server should send the message to all users in the channel, including the author

**Comment by dyladan** [comment]
on 3, why including the author?

**Comment by nathalie-tate** [comment]
so that the message will show up in the chatlog of the author. currently to do this, the client would need to send the message to itself (timestamping it, formating it to the server message protocol, etc). The server already does all this, no reason to be redundant

**Comment by dyladan** [comment]
ok

**Comment by dyladan** [comment]
If you get some time can you split this into 3 separate issues? It will help with organization. If you don't i can do it later.

**Comment by nathalie-tate** [comment]
yeah sure

**Comment by nathalie-tate** [comment]
created #6 #7 and #8
